apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-in
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true" # pass certificate to app
    nginx.ingress.kubernetes.io/auth-tls-secret: app/ca-secret # CA created as secret
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "off" # Enables verification of client certificates options: optional_no_ca,off,optional
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1" # The validation depth between the provided client certificate and the Certification Authority chain. (default: 1)
spec:
  ingressClassName: nginx
  rules:
  - host: test.localdev.me
    http:
      paths:
      - backend:
          service:
            name: app-mtls-svc
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - test.localdev.me
    secretName: localdev-tls