apiVersion: apps/v1
kind: Deployment
metadata:
  name:  app-mtls-dp
  namespace: app
  labels:
    app:  app-mtls
spec:
  selector:
    matchLabels:
      app: app-mtls
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-mtls
    spec:
      containers:
      - name: app-mtls
        image: josecyber/mtls-poc:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: app-mtls-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: app-mtls-svc
  namespace: app
spec:
  selector:
    app: app-mtls
  type: ClusterIP
  ports:
  - name: app-mtls
    protocol: TCP
    port: 8080
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-mtls-cfg
  namespace: app
data:
  PORT: "8080"